### ISSUE TITLE
If you want all results, you should rather use -1 than 100000

### ISSUE THREAD

**Issue by boogheta** [Guillaume-Levrier/PANDORAE#7]
Here: https://github.com/Guillaume-Levrier/PANDORAE/blob/c57a8c82074382f8970fe3b1814c58a56ac18d38/js/types.js#L692

Warning: the output result will be formatted differently

cf doc: https://github.com/medialab/hyphe/blob/master/doc/api.md#retrieve-and-search-webentities

**Comment by Guillaume-Levrier** [comment]
En fait je vais descendre à 5-10K je pense, parce que ça fait autant de noeuds dans le DOM + un nombre exponentiel de links, et donc ça va tuer pandorae qui ne va jamais réussir à calculer le graph. J'avais oublié de le modifier, thx pour la notif !

**Comment by boogheta** [comment]
OK, mais c'est un peu bizarre de prendre un nombre arbitraire d'éléments du corpus non?

**Comment by Guillaume-Levrier** [comment]
En vrai je pourrais prendre tous les éléments avec -1, garder les liens pour la génération de la heatmap, et juste ne pas les afficher dans le DOM vu qu'il y en a trop pour qu'ils soient intelligibles. Tu penses que ça aurait plus de sens ?

**Comment by boogheta** [comment]
yep!

**Comment by Guillaume-Levrier** [comment]
Ok, je fais ça aujourd'hui ou demain. Merci !
