### ISSUE TITLE
The electron build for Linux does not seem to work

### ISSUE THREAD

**Issue by boogheta** [Guillaume-Levrier/PANDORAE#8]
when downloading and starting it, it opens a windows with a blank page and only the two topleft buttons there, but not functional.

The log says:
```
./PANDORÆ: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by ./PANDORÆ)
/home/boogheta/Téléchargements/PANDORÆ-linux-x64/PANDORÆ: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /home/boogheta/Téléchargements/PANDORÆ-linux-x64/PANDORÆ)
Fontconfig warning: "/etc/fonts/fonts.conf", line 86: unknown element "blank"
/proc/self/exe: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /proc/self/exe)
/proc/self/exe: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /proc/self/exe)

```

**Comment by Guillaume-Levrier** [comment]
Thank you for submitting this issue. This [thread ](https://github.com/electron/electron/issues/15069) says this

> Electron requires a desktop environment.

Do you have a desktop environment ?

Apparently other linux users with desktop environments also have had similar problems, and an [issue](https://github.com/electron/electron/issues/16364) about this is still open. 

This seems to be an electron-related issue, not a PANDORÆ-related issue. Would you mind cloning the repo, installing the master branch with 

```
npm i
./node_modules/.bin/electron-rebuild
```

and telling me whether this works or not? 

Thanks for your help!

**Comment by boogheta** [comment]
The commands run smoothly, then if I run `npm run start` PANDORAE works, with the following logs
```
/home/boogheta/dev/PANDORAE/node_modules/electron/dist/electron: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /home/boogheta/dev/PANDORAE/node_modules/electron/dist/electron)
/home/boogheta/dev/PANDORAE/node_modules/electron/dist/electron: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /home/boogheta/dev/PANDORAE/node_modules/electron/dist/electron)
Fontconfig warning: "/etc/fonts/fonts.conf", line 86: unknown element "blank"
/proc/self/exe: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /proc/self/exe)
ATTENTION: default value of option force_s3tc_enable overridden by environment.
/proc/self/exe: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /proc/self/exe)

```

**Comment by Guillaume-Levrier** [comment]
I see. @diegantobass any chance we'd have a machine running a non-headless recent-ish linux version in the lab?

**Comment by diegantobass** [comment]
@Guillaume-Levrier doable within near future. How about you sew a head on one of the lab's ubuntu server ? #frankenstein

**Comment by Guillaume-Levrier** [comment]
@diegantobass how about we flash a USB drive with a linux dist and use it on our computers instead? I'm not doing this to cuicui, if that was what you were thinking about.

**Comment by diegantobass** [comment]
@Guillaume-Levrier actualy cuicui already has a head : it's a gnome

**Comment by Guillaume-Levrier** [comment]
Apparently the current build **works** on vanilla Ubuntu. I'm closing this issue for now, unless something new comes up.

**Comment by boogheta** [comment]
Hello there
I just tried to pull and restart: now it displays something, I got the fancy visualisation on homepage, and I can access the settings menu within Flux and connect to Hyphe or such. Although I can't seem to find how to use it then, and I still have in the shell the following log outputed regularily:
```
/proc/self/exe: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /proc/self/exe)
```

**Comment by Guillaume-Levrier** [comment]
@boogheta  the Hyphe section isn't documented in the wiki yet. The way to do it right now is to:
- enter a Hyphe endpoint (such as https://hyphe.medialab.sciences-po.fr/demo)
- click on check hyphe endpoint
- then if it is detected, click on "add to hyphe endpoints"
- then click on display
- then click on an endpoint in the list
- and then select a corpus.

Loaded corpuses will directly be available in menu->types->hyphotype

**Comment by boogheta** [comment]
Ha yes, it works!
I found it on my own up to the 4th point only, the list of available endpoints didn't seem clickable and I didn't try ;)
